### ISSUE TITLE
Payment then back to roseville escape gives an error

### ISSUE THREAD

**Issue by dunatotatos** [chiantific/Roseville#64]
Fatal error: Uncaught exception 'Exception' with message 'Invalid argument given. Expected integer for the $appointment_id : roseville.dunatotatos.com' in /var/www/Roseville/booking/application/models/appointments_model.php:255 Stack trace: #0 /var/www/Roseville/booking/application/controllers/appointments.php(287): Appointments_Model->get_row('roseville.dunat...') #1 [internal function]: Appointments->post_payment('roseville.dunat...') #2 /var/www/Roseville/booking/system/core/CodeIgniter.php(360): call_user_func_array(Array, Array) #3 /var/www/Roseville/booking/index.php(229): require_once('/var/www/Rosevi...') #4 {main} thrown in /var/www/Roseville/booking/application/models/appointments_model.php on line 255

**Comment by dunatotatos** [comment]
Merge with #65 
Same issue, different place

**Comment by dunatotatos** [comment]
After payment, goes to https://roseville.dunatotatos.com/booking/index.php/appointments/post_payment/roseville.dunatotatos.com

**Comment by dunatotatos** [comment]
Probably a bad configuration in backend. Company URL should start with http://, or the link is used as a relative URL.

#TODO

**Comment by dunatotatos** [comment]
Confirmed. Changing the value in backend fixes the issue.
